[package]
name = "pyworkingcopy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.20"
cpython = { version = "0.7", default-features = false }
cpython_ext = { path = "../../../../lib/cpython-ext", default-features = false }
pathmatcher = { path = "../../../../lib/pathmatcher" }
pymanifest = { path = "../pymanifest" }
pypathmatcher = { path = "../pypathmatcher" }
pystatus = { path = "../pystatus" }
pytreestate = { path = "../pytreestate" }
storemodel = { path = "../../../../lib/storemodel" }
workingcopy = { path = "../../../../lib/workingcopy" }
